version: '3.8'
services:
  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "22181:2181"

  kafka:
    build:
      context: .
      dockerfile: Kafka/Kafka.Dockerfile
    depends_on:
      - zookeeper
    ports:
      - "29092:29092"

  bots:
    build:
      context: .
      dockerfile: Bots.Dockerfile
    depends_on:
      - kafka

  ui-server:
    build:
      context: .
      dockerfile: Server.Dockerfile
    depends_on:
      - kafka
    ports:
      - "8080:8080"